name: athos_analytics
description: Flutter library for Athos Analytics
version: 0.0.1
homepage: https://athos-analytics.io

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^7.0.1
  package_info: ^2.0.2
  http: ^0.13.5
  json_annotation: ^4.7.0
  device_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.4.0
  build_runner: ^2.2.1

flutter: