name: athos_analytics
description: Flutter library for Athos Analytics
version: 0.0.2
homepage: https://athos-analytics.io

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  device_info_plus: ^9.1.2
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  json_serializable: ^6.7.1

flutter: